/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/wordpresses/{version}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get WordPress vulnerabilities by WordPress version
         * @description The WordPress version should have the dots removed. For example, 5.6.1 becomes 561.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description WordPress version */
                    version: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description successful operation */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["WordPress"][];
                    };
                };
                /** @description unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description authentication failure */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description too many requests */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/plugins/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get plugin vulnerabilities by plugin slug
         * @description The plugin slug is the directory name the plugin is given when installed in /wp-content/plugins/
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Plugin slug */
                    slug: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description successful operation */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Plugins"][];
                    };
                };
                /** @description unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description authentication failure */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description too many requests */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/themes/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get theme vulnerabilities by theme slug
         * @description The theme slug is the directory name the theme is given when installed in /wp-content/themes/
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Theme slug */
                    slug: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description successful operation */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Themes"][];
                    };
                };
                /** @description unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description authentication failure */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description too many requests */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get the user's plan status
         * @description Returns the user's plan status
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description successful operation */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": unknown;
                    };
                };
                /** @description unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description authentication failure */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description too many requests */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/all/latest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get last 20 vulnerabilities from database
         * @description Returns the last 20 vulnerabilities added to our database
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description successful operation */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description authentication failure */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description too many requests */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/wordpresses/latest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get last 20 WordPress vulnerabilities from database
         * @description Returns the last Plugin 20 vulnerabilities added to our database
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description successful operation */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description authentication failure */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description too many requests */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/plugins/latest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get last 20 Plugin vulnerabilities from database
         * @description Returns the last Plugin 20 vulnerabilities added to our database
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description successful operation */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description authentication failure */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description too many requests */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/plugins/{slug}/{version}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get plugin vulnerabilities by plugin slug filtered by version
         * @description The plugin slug is the directory name the plugin is given when installed in /wp-content/plugins/
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Plugin slug */
                    slug: string;
                    /** @description Plugin version */
                    version: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description successful operation */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Plugins"][];
                    };
                };
                /** @description unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description authentication failure */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description too many requests */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/themes/latest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get last 20 Theme vulnerabilities from database
         * @description Returns the last Theme 20 vulnerabilities added to our database
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description successful operation */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description authentication failure */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description too many requests */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/themes/{slug}/{version}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get theme vulnerabilities by theme slug filtered by version
         * @description The theme slug is the directory name the theme is given when installed in /wp-content/themes/
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Theme slug */
                    slug: string;
                    /** @description Theme version */
                    version: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description successful operation */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Themes"][];
                    };
                };
                /** @description unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description authentication failure */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description too many requests */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/vulnerabilities/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a single vulnerability by its ID
         * @description Returns the vulnerability data of a given ID
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Vulnerability ID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description successful operation */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description authentication failure */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description too many requests */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/batch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Batch requests
         * @description Returns the output of each request
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["BatchRequest"];
                };
            };
            responses: {
                /** @description successful operation */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BatchResponse"][];
                    };
                };
                /** @description unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description authentication failure */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description too many requests */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        WordPress: {
            "4.9.4"?: {
                /**
                 * Format: date-time
                 * @description the release date of the WordPress version
                 * @example 2018-02-06
                 */
                release_date?: string;
                /**
                 * @description the changelog URL of this WordPress version
                 * @example https://codex.wordpress.org/Version_4.9.4
                 */
                changelog_url?: string;
                /**
                 * @description the status of this WordPress release
                 * @example insecure
                 */
                status?: string;
                vulnerabilities?: {
                    /** @example 5e0c1ddd-fdd0-421b-bdbe-3eee6b75c919 */
                    id?: string;
                    /**
                     * @description old style vulnerability IDs, only older ones will have one
                     * @example 9021
                     */
                    old_id?: number;
                    /** @example WordPress <= 4.9.4 - Application Denial of Service (DoS) (unpatched) */
                    title?: string;
                    /** @example 2018-02-05T16:50:40.000Z */
                    created_at?: string;
                    /** @example 2020-09-22T07:24:12.000Z */
                    updated_at?: string;
                    /** @example 2018-02-05T00:00:00.000Z */
                    published_date?: string;
                    /**
                     * @description Enterprise only
                     * @example An application Denial of Service (DoS) was found to affect WordPress versions 4.9.4 and below. We are not aware of a patch for this issue.
                     */
                    description?: string;
                    /** @description Enterprise only */
                    poc?: string;
                    /** @example DOS */
                    vuln_type?: string;
                    references?: {
                        /** @example https://baraktawily.blogspot.fr/2018/02/how-to-dos-29-of-world-wide-websites.html */
                        url?: unknown[];
                        /** @example 2018-6389 */
                        cve?: unknown[];
                    };
                    /** @description Enterprise only */
                    cvss?: {
                        /** @example 7.5 */
                        score?: string;
                        /** @example CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H */
                        vector?: string;
                        /** @example high */
                        severity?: string;
                    };
                    /** @example false */
                    verified?: boolean;
                    /**
                     * @description What version was the vulnerability fixed/patched in.
                     * @example 4.9.5
                     */
                    fixed_in?: string;
                    /**
                     * @description What version was the vulnerability introduced in. This data is optional and may not always be available.
                     * @example 1.0
                     */
                    introduced_in?: string;
                }[];
            };
        };
        Plugins: {
            eshop?: {
                /** @example null */
                friendly_name?: string;
                /** @example 6.3.14 */
                latest_version?: string;
                /** @example 2015-10-13T11:07:00.000Z */
                last_updated?: string;
                /** @example false */
                popular?: boolean;
                vulnerabilities?: {
                    /** @example 14007aca-9172-4496-b921-0074deb20bc2 */
                    id?: string;
                    /** @example 7004 */
                    old_id?: number;
                    /** @example eShop - wp-admin/admin.php Multiple Parameter XSS */
                    title?: string;
                    /** @example 2014-08-01T10:59:06.000Z */
                    created_at?: string;
                    /** @example 2019-10-21T10:43:00.000Z */
                    updated_at?: string;
                    /** @example 2014-08-01T10:59:06.000Z */
                    published_date?: string;
                    /**
                     * @description Enterprise only
                     * @example The eshop WordPress plugin was affected by a wp-admin/admin.php Multiple Parameter XSS security vulnerability.
                     */
                    description?: string;
                    /**
                     * @description Enterprise only
                     * @example null
                     */
                    poc?: string;
                    /** @example XSS */
                    vuln_type?: string;
                    references?: {
                        /** @example https://seclists.org/bugtraq/2011/Aug/52 */
                        url?: unknown[];
                    };
                    /**
                     * @description Enterprise only
                     * @example null
                     */
                    cvss?: Record<string, never>;
                    /** @example false */
                    verified?: boolean;
                    /**
                     * @description What version was the vulnerability fixed/patched in.
                     * @example 6.2.9
                     */
                    fixed_in?: string;
                    /**
                     * @description What version was the vulnerability introduced in. This data is optional and may not always be available.
                     * @example null
                     */
                    introduced_in?: string;
                    /** @description Is this plugin closed? Removed from the plugin repository. */
                    closed?: {
                        /**
                         * @description A description why this plugin is closed
                         * @example Security issue.
                         */
                        closed_reason?: string;
                    };
                }[];
            };
        };
        Themes: {
            pagelines?: {
                /** @example null */
                friendly_name?: string;
                /** @example 1.4.6 */
                latest_version?: string;
                /** @example 2015-01-19T00:00:00.000Z */
                last_updated?: string;
                /** @example false */
                popular?: boolean;
                vulnerabilities?: {
                    /** @example 339a8975-c587-404e-813b-d624457f0cf9 */
                    id?: string;
                    /** @example 7763 */
                    old_id?: number;
                    /** @example Pagelines Theme <= 1.4.5 - Privilege escalation */
                    title?: string;
                    /** @example 2015-01-22T20:43:05.000Z */
                    created_at?: string;
                    /** @example 2019-10-21T12:46:04.000Z */
                    updated_at?: string;
                    /** @example 2015-01-22T20:43:05.000Z */
                    published_date?: string;
                    /**
                     * @description Enterprise only
                     * @example The pagelines WordPress theme was affected by a Privilege escalation security vulnerability.
                     */
                    description?: string;
                    /**
                     * @description Enterprise only
                     * @example null
                     */
                    poc?: string;
                    /** @example BYPASS */
                    vuln_type?: string;
                    references?: {
                        /** @example https://blog.sucuri.net/2015/01/security-advisory-vulnerabilities-in-pagelinesplatform-theme-for-wordpress.html */
                        url?: unknown[];
                    };
                    /**
                     * @description Enterprise only
                     * @example null
                     */
                    cvss?: Record<string, never>;
                    /** @example false */
                    verified?: boolean;
                    /**
                     * @description What version was the vulnerability fixed/patched in.
                     * @example 1.4.6
                     */
                    fixed_in?: string;
                    /** @description What version was the vulnerability introduced in. This data is optional and may not always be available. */
                    introduced_in?: string;
                    /** @description Is this theme closed? Removed from the theme repository. */
                    closed?: {
                        /**
                         * @description A description why this plugin is closed
                         * @example Security issue.
                         */
                        closed_reason?: string;
                    };
                }[];
            };
        };
        Status: {
            /** @example enterprise */
            plan?: string;
            requests_limit?: number;
            requests_remaining?: number;
            requests_reset?: number;
        };
        BatchRequest: {
            /**
             * @description An array of strings representing the batched requests.
             * @example [
             *       "plugins/eshop",
             *       "themes/Pagelines",
             *       "wordpresses/494"
             *     ]
             */
            requests?: string[];
        };
        BatchResponse: {
            /**
             * @description An array of objects for each response.
             * @example [
             *       {
             *         "eshop": {
             *           "friendly_name": null,
             *           "latest_version": "6.3.14",
             *           "last_updated": "2015-10-13T11:07:00.000Z",
             *           "popular": false,
             *           "vulnerabilities": [
             *             {
             *               "id": "14007aca-9172-4496-b921-0074deb20bc2",
             *               "old_id": 7004,
             *               "title": "eShop - wp-admin/admin.php Multiple Parameter XSS",
             *               "created_at": "2014-08-01T10:59:06.000Z",
             *               "updated_at": "2019-10-21T10:43:00.000Z",
             *               "published_date": "2014-08-01T10:59:06.000Z",
             *               "description": "The eshop WordPress plugin was affected by a wp-admin/admin.php Multiple Parameter XSS security vulnerability.",
             *               "poc": null,
             *               "vuln_type": "XSS",
             *               "references": {
             *                 "url": "https://seclists.org/bugtraq/2011/Aug/52"
             *               },
             *               "cvss": null,
             *               "verified": false,
             *               "fixed_in": "6.2.9",
             *               "introduced_in": null,
             *               "closed": {
             *                 "closed_reason": "Security issue."
             *               }
             *             }
             *           ]
             *         }
             *       },
             *       {
             *         "pagelines": {
             *           "friendly_name": null,
             *           "latest_version": "1.4.6",
             *           "last_updated": "2015-01-19T00:00:00.000Z",
             *           "popular": false,
             *           "vulnerabilities": [
             *             {
             *               "id": "339a8975-c587-404e-813b-d624457f0cf9",
             *               "old_id": 7763,
             *               "title": "Pagelines Theme <= 1.4.5 - Privilege escalation",
             *               "created_at": "2015-01-22T20:43:05.000Z",
             *               "updated_at": "2019-10-21T12:46:04.000Z",
             *               "published_date": "2015-01-22T20:43:05.000Z",
             *               "description": "The pagelines WordPress theme was affected by a Privilege escalation security vulnerability.",
             *               "poc": null,
             *               "vuln_type": "BYPASS",
             *               "references": {
             *                 "url": "https://blog.sucuri.net/2015/01/security-advisory-vulnerabilities-in-pagelinesplatform-theme-for-wordpress.html"
             *               },
             *               "cvss": null,
             *               "verified": false,
             *               "fixed_in": "1.4.6",
             *               "introduced_in": null,
             *               "closed": {
             *                 "closed_reason": "Security issue."
             *               }
             *             }
             *           ]
             *         }
             *       },
             *       {
             *         "4.9.4": {
             *           "release_date": "2018-02-06",
             *           "changelog_url": "https://codex.wordpress.org/Version_4.9.4",
             *           "status": "insecure",
             *           "vulnerabilities": [
             *             {
             *               "id": "5e0c1ddd-fdd0-421b-bdbe-3eee6b75c919",
             *               "old_id": 9021,
             *               "title": "WordPress <= 4.9.4 - Application Denial of Service (DoS) (unpatched)",
             *               "created_at": "2018-02-05T16:50:40.000Z",
             *               "updated_at": "2020-09-22T07:24:12.000Z",
             *               "published_date": "2018-02-05T00:00:00.000Z",
             *               "description": "An application Denial of Service (DoS) was found to affect WordPress versions 4.9.4 and below. We are not aware of a patch for this issue.",
             *               "poc": "string",
             *               "vuln_type": "DOS",
             *               "references": {
             *                 "url": "https://baraktawily.blogspot.fr/2018/02/how-to-dos-29-of-world-wide-websites.html",
             *                 "cve": "2018-6389"
             *               },
             *               "cvss": {
             *                 "score": 7.5,
             *                 "vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
             *                 "severity": "high"
             *               },
             *               "verified": false,
             *               "fixed_in": "4.9.5",
             *               "introduced_in": "1.0"
             *             }
             *           ]
             *         }
             *       }
             *     ]
             */
            responses?: Record<string, never>[];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
